spring:
  application:
    name: covid-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/covid
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 4869
  jpa: # show the generated SQL
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8181

pagehelper:
  helper-dialect: PostgreSQL
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.covid.backend.dao: debug